# Generated by Django 5.2 on 2026-03-19 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicaoVeiculoTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('arquivoid', models.CharField(db_index=True, max_length=256)),
                ('medicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telemetria.medicao')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telemetria.veiculo')),
            ],
        ),
    ]
